config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers
  end

  namespace :api do
    resources :questions do
      resources :answers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  def create
    answer = Answer.new(answer_params)

    if answer.save!
      redirect_to question_path(answer.question)
    else
      render :new
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :question_id)
  end
end

app/controllers/api/answers_controller.rb
class Api::AnswersController < Api::ApiController

  def index
    @question = Question.find(params[:question_id])
    render json: @question.answers
  end

  def create
    answer = Answer.new(answer_params)

    if answer.save!
      head :ok
    else
      head :bad_request
    end
  end

  private

  def answer_params
    temp = params.require(:answer).permit(:body, :question_id)
    temp[:question_id] ||= params[:question_id]

    temp
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
  skip_forgery_protection
end

app/controllers/api/questions_controller.rb
class Api::QuestionsController < Api::ApiController
  def index
    render json: Question.all
  end

  def show
    render json: Question.find(params[:id])
  end

  def create
    question = Question.new(question_params)

    if question.save!
      head :ok
    else
      head :bad_request
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    question = Question.new(question_params)

    if question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/new.html.erb
<%= link_to "< Wróc do pytania", question_path(@question) %>
<h1>Odpowiadasz na pytanie</h1>
<h3><%= @question.title %></h3>

<%= simple_form_for [@question, @answer] do |f| %>
<%= f.input :body %>
<%= f.input :question_id, as: :hidden %>
<%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DunnoServeur</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/index.html.erb
<h1>Pytania</h1>
<%= link_to "Dodaj pytanie", new_question_path, class: "btn btn-primary" %>
<% @questions.each do |question| %>
  <div class="card my-2" style="">
    <div class="card-body">
      <h5 class="card-title"><%= question.title %></h5>
      <p class="card-text"><%= question.body %></p>
      <%= link_to "Przejdż do strony pytania", question_path(question), class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>Nowe pytanie</h1>
<%= simple_form_for @question do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.button :submit %>
<% end %>

app/views/questions/show.html.erb
<%= link_to "< Wróc do wszystkich pytan", questions_path %>
<h1>Odpowiedzi na pytanie</h1>

<h2><%= @question.title %></h2>
<h4><%= @question.body %></h4>

<%= link_to "Dodaj odpowiedz", new_question_answer_path(@question), class: "btn btn-success" %>

<% @question.answers.each do |answer| %>
  <div class="card my-2" style="">
    <div class="card-body">
      <p class="card-text"><%= answer.body %></p>
    </div>
  </div>
<% end %>